export default [
  'About',
  'AboutSL',
  'CompilationIVArtistInfo',
  'Contact',
  'CookiePolicy',
  'CookieSettings',
  'DanceParty',
  'Home',
  'LifeInLetters',
  'MadeWithSoundLibrary',
  'MailingList',
  'NotFound',
  'ReactConsulting',
  'Support',
  'TracksOverview',
]
