export { default as About } from './About'
export { default as BerlinStockPhotos } from './BerlinStockPhotos'
export { default as Contact } from './Contact'
export { default as Prints } from './Prints'
export { default as NotFound } from './NotFound'
