import { IContentItem } from '../index'

function modelize(rawContentItem: any): IContentItem {
  return {
    acceptingDonations: rawContentItem.acceptingDonations || false,
    aside: rawContentItem.aside || '',
    attachments: rawContentItem.attachments || '',
    attachmentTo: rawContentItem.attachmentTo || '',
    attribution: rawContentItem.attribution || '',
    attributionLink: rawContentItem.attributionLink || '',
    audioFilename: rawContentItem.audioFilename || '',
    badgeText: rawContentItem.badgeText || '',
    blurb: rawContentItem.blurb || '',
    category: rawContentItem.category || '',
    date: rawContentItem.date || '',
    description: rawContentItem.description || '',
    displayCategory: rawContentItem.displayCategory || '',
    downloadFile: rawContentItem.downloadFile || '',
    duration: rawContentItem.duration || '',
    externalLinkText: rawContentItem.externalLinkText || '',
    externalLinkUrl: rawContentItem.externalLinkUrl || '',
    fileSize: rawContentItem.fileSize || '',
    fixedPrice: rawContentItem.fixedPrice || '',
    flexPriceChoices: rawContentItem.flexPriceChoices || '',
    flexPriceMinimum: rawContentItem.flexPriceMinimum || '',
    flexPriceRecommended: rawContentItem.flexPriceRecommended || '',
    hasFixedPrice: rawContentItem.hasFixedPrice || false,
    id: rawContentItem.id || '',
    isDigitalProduct: rawContentItem.isDigitalProduct || false,
    isPhysicalProduct: rawContentItem.isPhysicalProduct || false,
    keyArt: rawContentItem.keyArt || '',
    keyArtFullPath: rawContentItem.keyArtFullPath || '',
    keyArtThumbnailFullPath: rawContentItem.keyArtThumbnailFullPath || '',
    note: rawContentItem.note || '',
    order: rawContentItem.order || '',
    physicalFormats: rawContentItem.physicalFormats || '',
    preview: rawContentItem.preview || false,
    project: rawContentItem.project || '',
    properties: rawContentItem.properties || '',
    published: rawContentItem.published || false,
    relatedContent: rawContentItem.relatedContent || '',
    relatedContentLink: rawContentItem.relatedContentLink || '',
    releaseDate: rawContentItem.releaseDate || '',
    releasePhase: rawContentItem.releasePhase || '',
    secondaryAttribution: rawContentItem.secondaryAttribution || '',
    secondaryAttributionLink: rawContentItem.secondaryAttributionLink || '',
    secondaryTitle: rawContentItem.secondaryTitle || '',
    slug: rawContentItem.slug || '',
    sticky: rawContentItem.sticky || false,
    tags: rawContentItem.tags || '',
    title: rawContentItem.title || '',
    titleWrapping: rawContentItem.titleWrapping || '',
    type: rawContentItem.type || '',
  }
}

export default modelize
